### ISSUE TITLE
grunt init not working & no gulpfile found

### ISSUE THREAD

**Issue by bsesic** [nn-medienagentur/kicktemp#11]
There comes an error initializing grunt with "grunt init".

```
(node:12792) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Warning: Task "init" not found. Use --force to continue.

Aborted due to warnings.
```

I did run "npm install -g grunt-cli" and I also updated graceful-fs.

Additional there is the error after running gulp.
`
No gulpfile found
`

**Comment by nielsnuebel** [comment]
Hi Benjamin,

i'll create a new version this weekend only with gulp.
